### ISSUE TITLE
Automate profile updates

### ISSUE THREAD

**Issue by stefan-kolb** [stefan-kolb/paas-profiles#118]
- [ ] Rewrite consistency checks etc.

**Comment by stefan-kolb** [comment]
- https://www.openshift.com/features/cartridges.html

**Comment by JohannesRudolph** [comment]
Would this e.g. entail automatically updating framework/runtime support for Cloud Foundry/OpenShift providers? E.g. automatically fixing a lot of the consistency warnings currently encountered. Alternatively, you might want to reconsider whether CF/OpenShift should have an "Buildpacks" support and then we could centrally list all buildpacks available (e.g. covers Heroku as well).  Or just set them to "any" (because one can run write a buildpack for any framework/language yourself)

**Comment by stefan-kolb** [comment]
Yes, ideally it would.
