### ISSUE TITLE
Add more filtering capabilities

### ISSUE THREAD

**Issue by stefan-kolb** [stefan-kolb/paas-profiles#59]
Add missing attributes, such as pricing etc.
Cluster filtering on attributes to keep usability.

**Comment by analog-nico** [comment]
Criteria which are very important for me are:

- [ ] Sticky Sessions (Load balancer routes requests of the same user always to the same instance - especially required for Meteor apps but for my custom app as well)
- [ ] Zero-Downtime Deployment
- [ ] E.U. ready (Since the US EU Safe Harbor Agreement was cancelled it is difficult to export data to the US. For EU companies this is an important aspect)
